# Generated by Django 5.2.5 on 2025-09-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('tools', 'Tools'), ('shoes', 'Shoes')], default='shirt', max_length=20),
        ),
    ]
